#ifndef DEFS_HPP
#define DEFS_HPP
#pragma once

#include <utility>
#include <vector>

//=============================================================================
// DO NOT EDIT THIS FILE
//=============================================================================

/**
 * The tile structure.
 */
struct Tile
{
    ///< Set to \c true if the tile represents a wall.
    bool     wall  = false;
    ///< Number of marks on the tile. Always \c zero if \c wall is \c true.
    unsigned marks = 0u;
};

/**
 * The position structure.
 */
struct Position
{
    ///< The position on the x axis.
    int x = 0;
    ///< The position on the y axis.
    int y = 0;
};

/**
 * Directions for the robot.
 */
enum class Direction
{
    North,
    East,
    South,
    West,
};

//=============================================================================
// DO NOT EDIT THIS FILE
//=============================================================================

#endif // DEFS_HPP
