#include "errors.hpp"

//=============================================================================
// DO NOT EDIT THIS FILE
//=============================================================================

#ifdef __unix__
#  define ANSI_RED(STR)     "\x1b[31m" << STR << "\x1b[39m"
#  define ANSI_YELLOW(STR)  "\x1b[33m" << STR << "\x1b[39m"
#else
// Sorry Windows, your terminal sucks. No colours for you.
#  define ANSI_RED(STR)     STR
#  define ANSI_YELLOW(STR)  STR
#endif

//=============================================================================
// DO NOT EDIT THIS FILE
//=============================================================================

[[noreturn]]
void Complain::_croak(const std::string& what, const std::string& msg,
        const std::string& details)
{
#if COMPLAIN_EXCEPTIONS
    UNUSED(details);
    throw std::runtime_error(what + ": " + msg);
#else
    std::cerr << ANSI_RED(what) << "\n";
    std::cerr << ANSI_YELLOW(msg) << ": " << details << "\n";
    std::exit(1);
#endif
}

//=============================================================================
// DO NOT EDIT THIS FILE
//=============================================================================
